spring.application.name=budget-management-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/master
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.default_schema=DB0001

# tells Hibernate (which is the default JPA implementation in Spring Boot) how to translate its generic SQL into the specific SQL dialect of PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# controls how Hibernate handles database schema changes (DDL = Data Definition Language, like CREATE, ALTER, etc.)
spring.jpa.hibernate.ddl-auto=update

mybatis.mapper-locations=classpath:mapper/*.xml